### ISSUE TITLE
[Feature Request] Command cooldowns

### ISSUE THREAD

**Issue by 1chiSensei** [kangalioo/poise#1]

**Comment by 1chiSensei** [comment]
For example: you're fetching data from an external api with very strict ratelimits. And you'd want your command to only be used once per minute.

**Comment by Leastrio** [comment]
I would love to see a cooldown system like [discord.py](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=cooldown#discord.ext.commands.cooldown) with cooldowns for channels, guilds, users, or members.

**Comment by kangalioo** [comment]
Would the cool down system need to have support for cool down buckets? I.e. group commands into buckets whose cool down is shared.

If cool down can be per command, that would be easier to implement and I could start working on it even with the library not having fleshed out command group support

**Comment by Leastrio** [comment]
I don't plan on having grouped commands, so per command is perfect for me.

**Comment by SpyrosRoum** [comment]
Old-ish issue but I'd like to mention that I was working with discord.py for multiple years (doing mostly commissions) and I never had to use anything that's not per command cooldown

**Comment by kangalioo** [comment]
I created an implementation in [a feature branch](https://github.com/kangalioo/poise/commits/command-id). You can configure cooldowns like this:

```rust
// Numbers are in seconds
#[poise::command(
    global_cooldown = 1,
    user_cooldown = 1,
    guild_cooldown = 1,
    channel_cooldown = 1,
    member_cooldown = 1,
)]
```

When a cooldown limit is hit, the `cooldown_hit` callback on FrameworkOptions is invoked with the `Context` and a `std::time::Duration` for the remaining cooldown time. By default, it prints `You're too fast. Please wait {} seconds before retrying`.

Currently, there is no equivalent to discord.py's Category and Role cooldown buckets, because they seem a bit exotic and niche for me. Although support can be added later if needed.

---

Any feedback on this design, is it ergonomic?

**Comment by kangalioo** [comment]
Merged into master

**Comment by DuckyBlender** [comment]
> ```rust
> #[poise::command(
>     global_cooldown = 1,
>     user_cooldown = 1,
>     guild_cooldown = 1,
>     channel_cooldown = 1,
>     member_cooldown = 1,
> )]
> ```

This is amazing, so simple yet so useful. Thanks for this
