### ISSUE TITLE
PopArgument problem

### ISSUE THREAD

**Issue by sadorowo** [kangalioo/poise#162]
Hello. I created `theme` command for my bot. It has for now only one subcommand named `success`.

When I'm using slash command, everything is working fine. But converting argument in prefixed commands doesn't work. Maybe I have broken PopArgument implementation?

Command input:
```yaml
.theme success #2f3136
```

Command code: 
```rust
use crate::database::guild_config::GuildConfig;
use crate::language::handler::LanguageHandler;
use crate::theme::embeds::Embeds;
use crate::models::color::Color;
use crate::commands::Context;

#[poise::command(
slash_command,
prefix_command,
category = "config",
aliases("th", "themed", "emb", "embeds"),
subcommands("success"),
required_permissions = "MANAGE_GUILD",
)]
// _prefix is here for informational purposes, if I used e.g. .theme unknown, the framework would return a TooManyArguments error 
pub async fn theme(ctx: Context<'_>, _prefix: String) -> Result<(), String> {
    let lang: LanguageHandler = LanguageHandler::from_context(ctx);
    Err(lang.translate("subcommand_use"))
}

#[poise::command(
slash_command,
prefix_command,
category = "config",
aliases("succ", "s"),
required_permissions = "MANAGE_GUILD",
)]
async fn success(
    ctx: Context<'_>,
    color: Color
) -> Result<(), String> {
    let mut config: GuildConfig = GuildConfig::from_context(&ctx).await;
    let lang: LanguageHandler = LanguageHandler::from_context(ctx);
    let mut embeds: Embeds = Embeds::from_context(ctx);

    config.theme.color_success = color.0;
    match config.save(ctx).await {
        Ok(_) => {
            let embed = embeds.success(
                &lang.translate("embed_title.theme.color_change_success"),
                &lang.translate("theme.color_change_success"),
            ).await;

            embeds.send(embed).await;
            Ok(())
        }
        Err(_) => return Err(lang.translate("theme.color_change_error")),
    }
}
```

Color struct and traits implementation:
```rust
use poise::serenity_prelude::{
    ArgumentConvert, ChannelId,
    CommandOptionType, Context,
    CreateApplicationCommandOption, GuildId,
    json::Value, Message,
};
use poise::{ApplicationCommandOrAutocompleteInteraction, async_trait, CommandParameterChoice, SlashArgError, SlashArgument, PopArgument, TooFewArguments};
use std::error::Error;

#[derive(Debug)]
pub struct Color(pub u32);

#[async_trait]
impl ArgumentConvert for Color {
    type Err = String;

    async fn convert(
        _ctx: &Context,
        _guild_id: Option<GuildId>,
        _channel_id: Option<ChannelId>,
        s: &str,
    ) -> Result<Self, Self::Err> {
        let s = s.trim_start_matches(&['#', '0', 'x']);
        let color = u32::from_str_radix(s, 16).map_err(|_| "invalid color")?;

        Ok(Color(color))
    }
}

impl std::fmt::Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let color = format!("{:06x}", self.0);
        f.write_str(&color)
    }
}

#[async_trait]
impl SlashArgument for Color {
    async fn extract(
        ctx: &Context,
        _: ApplicationCommandOrAutocompleteInteraction<'_>,
        value: &Value,
    ) -> Result<Self, SlashArgError> {
        let color = value.as_str().ok_or(SlashArgError::CommandStructureMismatch("expected str"))?;
        let color = Color::convert(
            ctx,
            None,
            None,
            color,
        ).await.map_err(|_| SlashArgError::CommandStructureMismatch("invalid color"))?;

        Ok(color)
    }

    fn create(builder: &mut CreateApplicationCommandOption) {
        builder.kind(CommandOptionType::String);
    }

    fn choices() -> Vec<CommandParameterChoice> {
        Vec::new()
    }
}

#[async_trait]
impl<'a> PopArgument<'a> for Color {
    async fn pop_from(
        arg: &'a str,
        attachment_index: usize,
        ctx: &Context,
        msg: &Message,
    ) -> Result<(&'a str, usize, Self), (Box<dyn Error + Send + Sync>, Option<String>)> {
        if arg.is_empty() {
            return Err((Box::new(TooFewArguments), None));
        }

        let color = Color::convert(
            ctx,
            msg.guild_id,
            Some(msg.channel_id),
            arg,
        ).await.map_err(|e| (e.into(), None))?;

        Ok((arg, attachment_index, color))
    }
}
```

When I'm using prefixed commands, I'm getting **TooManyArguments**.

I tried debugging, color is always u32, as expected.

What am I doing wrong?

**Comment by kangalio** [comment]
Can you show how you're invoking the text command (prefix command)? Like, what you're writing in Discord?

**Comment by sadorowo** [comment]
```yaml
.theme success #2f3136
```

**Comment by kangalio** [comment]
Oh nevermind I see the problem. You did implement PopArgument incorrectly. The returns &str must be the _remaining_ string after popping your argument off. But you're returning the original string. So, after parsing `Color`, the string of arguments still contains the `#2f3136` but all parameters of the command have already been parsed -> too many arguments.

To solve this, just delete your PopArgument implementation. It's redundant because you already implemented ArgumentConvert (see [docs](https://docs.rs/poise/latest/poise/macros/attr.command.html#function-parameters)).

You can delete SlashArgument too (it's also redundant because it's auto-generated from the ArgumentConvert impl).

And, if you want, you can shorten the code even further by implementing FromStr instead of ArgumentConvert. Every FromStr automatically has an ArgumentConvert impl, so implementing FromStr is easier if you don't need ArgumentConvert's extra capabilities, i.e. async and accessing Discord context.

**Comment by sadorowo** [comment]
oh okay, thanks for help, closing.

**Comment by sadorowo** [comment]
I followed your instructions and now I'm getting another trait implementation error.
Code:
```rust
use std::str::FromStr;

#[derive(Debug)]
pub struct Color(pub u32);

impl std::fmt::Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let color = format!("{:06x}", self.0);
        f.write_str(&color)
    }
}

impl FromStr for Color {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let color = match s {
            "red" => 0xFF0000,
            "green" => 0x00FF00,
            "blue" => 0x0000FF,
            "yellow" => 0xFFFF00,
            "cyan" => 0x00FFFF,
            "magenta" => 0xFF00FF,
            "white" => 0xFFFFFF,
            "black" => 0x000000,
            _ => match u32::from_str_radix(s.trim_start_matches(&['#', '0', 'x']), 16) {
                Ok(color) => color,
                Err(_) => return Err("Invalid color".to_string()),
            },
        };

        Ok(Color(color))
    }
}
```
![Zrzut ekranu 2023-05-5 o 11 58 38](https://user-images.githubusercontent.com/97941280/236428888-99b0ec06-b65d-454a-9e61-95bdedeb4fac.png)
![Zrzut ekranu 2023-05-5 o 11 59 34](https://user-images.githubusercontent.com/97941280/236429117-0ae2f091-e7d7-4a00-8d77-f4a01b824a18.png)
![Zrzut ekranu 2023-05-5 o 11 59 50](https://user-images.githubusercontent.com/97941280/236429149-59f06e12-f126-49ce-b93c-d47248ce0361.png)

**Comment by kangalio** [comment]
This part is important:

![Screenshot_20230505_120920](https://user-images.githubusercontent.com/21220820/236431023-982fe36d-7203-477c-80ee-b9ed942283ad.png)
![image](https://user-images.githubusercontent.com/21220820/236431267-56e407ac-761a-4cd9-8fe7-b76f7247f176.png)

Your error type is String, which does not implement std::error::Error, but the error type must implement std::error::Error (so that it can be stored in [FrameworkError::ArgumentParse](https://docs.rs/poise/latest/poise/structs/enum.FrameworkError.html#variant.ArgumentParse) and downcasted). You can use `Box<dyn std::error::Error + Send + Sync>` as error type instead

**Comment by sadorowo** [comment]
thanks, I'm still learning Rust, sorry for taking time & thanks for fast reply.
