### ISSUE TITLE
Ping discord API similar to `client.ws.ping` in discord.js

### ISSUE THREAD

**Issue by onlycs** [kangalioo/poise#189]
Ideally, it should live on `poise::Context` and return a `std::time::Duration`.

```rs

#[poise::command(slash_command)]
pub async fn my_command(ctx: Context<'_>) -> Result<()> {
    ...
    
    let latency: Duration = ctx.api_ping();
    ctx.say(format!("Api Ping: {}ms", latency.as_millis())).await?;
    
    ...
    Ok(())
}
```

I'm not sure if there is another way to get the api ping, I wasn't able to find anything in the documentation.

**Comment by scottbot95** [comment]
Something worth considering adding. Is the use-case just for debugging/metrics to help understand bot performance?

It is _technically_ possible right now, but it's a little gross (see [serenity example](https://github.com/serenity-rs/serenity/blob/fe5febf9d21d77202737e00ca91066adb7f35f18/examples/e05_command_framework/src/main.rs#L468-L500))

 It's slightly better with poise than base serenity since you can get the `ShardManager` by `ctx.framework().shard_manager()` instead of trying to get it out of the `serenity::Context::Data`
