### ISSUE TITLE
Quickstart crashes on runtime / cannot use commands

### ISSUE THREAD

**Issue by L1ghtingBolt** [kangalioo/poise#67]
I get this error when I try to run the Quickstart (I've already setted the env variable)
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Gateway(DisallowedGatewayIntents)', src\main.rs:43:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\learn_rust.exe` (exit code: 101)
```

**Comment by kangalio** [comment]
The quickstart sets the MESSAGE_CONTENT intent in order to process text commands. This intent needs to be enabled in the Discord dashboard:

![Screenshot_20220501_160955](https://user-images.githubusercontent.com/21220820/166149625-02093952-b613-4cd1-b643-ab56d9b4782e.png)

(The intent _is_ being enforced right now; that box is plain false)

---

Inspired by this issue, I reworked the quickstart in 8efa619a97c41d86af7d4fa2f3b9f356030774ca to not require MESSAGE_CONTENT and cater to slash commands by default (which most people probably want to use poise for by now). Feel free to tell me what you think about the new quickstart

**Comment by L1ghtingBolt** [comment]
That worked, thanks. Tho, now when I run it I can't find the age slash command, just a wonterful_command that does not do anything.

**Comment by kangalio** [comment]
wonderful_command is from serenity's [e14_slash_commands example](https://github.com/serenity-rs/serenity/blob/current/examples/e14_slash_commands/src/main.rs)... Try restarting your Discord client, it seems to have an outdated state of commands

**Comment by L1ghtingBolt** [comment]
> wonderful_command is from serenity's [e14_slash_commands example](https://github.com/serenity-rs/serenity/blob/current/examples/e14_slash_commands/src/main.rs)... Try restarting your Discord client, it seems to have an outdated state of commands

No result. Even after a day of the bot turned off and Discord client restarted, In can only see wonderful_command. Thanks for helping me, tho!

**Comment by kangalio** [comment]
Weird.. and you did fill in the correct guild ID in the quickstart?

**Comment by L1ghtingBolt** [comment]
Lemme check

**Comment by Bloectasy** [comment]
@L1ghtingBolt may you see if the application commands are available in the Guild settings > integration > your bot

**Comment by L1ghtingBolt** [comment]
> @L1ghtingBolt may you see if the application commands are available in the Guild settings > integration > your bot

Yea, they are on.

**Comment by kangalio** [comment]
This may be a Discord bug: https://github.com/discord/discord-api-docs/issues/4856

**Comment by Bloectasy** [comment]
This is indeed a discord bug with commands permissions v2 guilds. For now try using global commands instead, or use your mobile device.

**Comment by kangalio** [comment]
Since the quickstart doesn't require MESSAGE_CONTENT anymore, and the only remaining issue is a Discord bug, I will close this issue
