### ISSUE TITLE
Add serenity crash course to docs

### ISSUE THREAD

**Issue by BuyMyMojo** [kangalioo/poise#94]
I'm trying to send a DM to a user provided in a command but `user.create_dm_channel();` and `user.direct_message();` both require a CacheHttp object. Looking through the docs and the examples I don't see any mention of this.

Could you add some examples on how to use those functions in the docs and in this issue for me too please.

**Comment by kangalio** [comment]
Sure. I should add a whole section about serenity specific knowledge since people often run into this

Gonna use this issue as a brainstorming canvas:
- `impl CacheHttp`, `impl AsRef<Http>` etc with `ctx.discord()`
- gateway intents: default is non_privileged, need to OR with non_privileged to add to it, GUILD_MESSAGES is different than MESSAGE_CONTENT, privileged intents in general
- HTTP events without trigger by storing CacheAndHttp (from Context in user_data_setup, or framework.client().cache_and_http i guess if I add that)
- some methods are on the Id types only

To give a quick answer now to your question: serenity's function take `impl CacheHttp` which means "anything that implements the CacheHttp trait" (the full list of implementors is [in its docs](https://docs.rs/serenity/0.11.2/serenity/http/trait.CacheHttp.html#foreign-impls)) The type you're gonna use most is the serenity Context struct which you can access from poise Context via [`ctx.discord()`](https://docs.rs/poise/latest/poise/enum.Context.html#method.discord)

**Comment by BuyMyMojo** [comment]
That worked perfeactly! thanks

**Comment by BuyMyMojo** [comment]
Where would you be able to get a cache when handeling new messages?

```rust
async fn event_listener(
    ctx: &serenity::Context,
    event: &poise::Event<'_>,
    _framework: poise::FrameworkContext<'_, Data, Error>,
    _user_data: &Data,
) -> Result<(), Error> {
    match event {
            poise::Event::Message { new_message } => {
                println!("{}", new_message.content);
                new_message.reply_mention(ctx, "gg").await?;
        }
        _ => {}
    }

    Ok(())
}
```

EDIT:
I figured it out... appologies for the pointless question!

Edited code block to reflect this.

**Comment by kangalio** [comment]
66bccc51ac4c11727df2090b613c994a1ce74878

Haven't got feedback yet and its probably suboptimally written and incomplete but its the best I can think of right now
