### ISSUE TITLE
Use `log` or `tracing` crate instead of `println!` and `eprintln!`

### ISSUE THREAD

**Issue by Erik1000** [kangalioo/poise#99]
I've noticed that `poise` uses `println!` as well as `eprintln!`.
This is bad, because this can't make use of a log backend like `env_logger` which formats logs in a nice way. This might lead to cases where a warning is missed, because it is just plain text and can't be distinguished from other (non warning) logs. E.g. I've just had a hard time finding this warning: <https://github.com/kangalioo/poise/blob/3ad61d4d1c51334b33a6bc362b129fb0e70ea514/src/framework/mod.rs#L287>

**Comment by kangalio** [comment]
True, that should be changed. I'm open for PRs I don't have much time myself

**Comment by kangalio** [comment]
What do you think of the `println!()` calls in the [default on_error function](https://github.com/kangalioo/poise/blob/develop/src/builtins/mod.rs#L27-L135)? This function is intended as a starting building block for new users, hence I decided to use println because that's easiest and most hassle-free since it doesn't require a logging library set up. What do you think?

**Comment by Erik1000** [comment]
I think it should use the logging/tracing library as well. Setting up a logger/tracer is a one liner and serenity already depends and uses the tracing crate. Maybe it would be a good idea to have an example logging/tracing setup in the docs for new users but other then that I think it’s fine.

**Comment by kangalio** [comment]
c29791af4290552ee646e04c8a117509fa3f0718
